# Generated by Django 4.1.5 on 2023-02-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='articles',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
        ),
    ]
